"""update story id

Revision ID: 020000d660dd
Revises: 377d9c240067
Create Date: 2024-10-18 15:47:18.232957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020000d660dd'
down_revision = '377d9c240067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('story_id', sa.Integer(), nullable=True))
        batch_op.drop_column('storyId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storyId', sa.INTEGER(), nullable=True))
        batch_op.drop_column('story_id')

    # ### end Alembic commands ###
