"""new

Revision ID: 20c08922be25
Revises: 020000d660dd
Create Date: 2024-10-18 17:04:42.939340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c08922be25'
down_revision = '020000d660dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_authors_story_id_stories'), 'stories', ['story_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_authors_story_id_stories'), type_='foreignkey')

    # ### end Alembic commands ###
